### ISSUE TITLE
服务器中报异常：QXcbConnection: Could not connect to display 

### ISSUE THREAD

**Issue by whirlys** [tensorlayer/tensorlayer-chinese#23]
我在 windows下通过 xshell 访问 centos，在 centos 中运行 example 中的 tutorial_mnist.py 就报异常了：`QXcbConnection: Could not connect to display `
**原因**应该是服务器中不能运行 GUI 程序
**错误的位置**应该是 tutorial_mnist.py 中第 390 行左右用到的 tl.visualize ，再进去就是 tl.visualize 这个文件中的 `import matplotlib.pyplot as plt `
**我的解决方法**：在 tl.visualize 源码中把被注释掉的 `matplotlib.use('Agg')` 去掉注释，就可以了。
现在我想请问一下**有没有其他途径可以解决这个问题**呢？

**Comment by zsdonghao** [comment]
你可以在你的代码最上面执行`matplotlib.use('Agg')`

**Comment by zsdonghao** [comment]
更多信息可见 FQA：http://tensorlayer.readthedocs.io/en/latest/user/more.html#fqa
