### ISSUE TITLE
python3.6环境下导入出错

### ISSUE THREAD

**Issue by Cheneng** [tensorlayer/tensorlayer-chinese#27]
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

是3.6版本的python不兼容吗

**Comment by zsdonghao** [comment]
这是个tensorflow安装问题？

**Comment by zsdonghao** [comment]
@Cheneng 你好，若没有什么问题，这边先关闭了～
