### ISSUE TITLE
当使用分布式session的时候无法使用checkpoint

### ISSUE THREAD

**Issue by ning180** [tensorlayer/tensorlayer-chinese#32]
当我用文档提供的例子tutorial_mnist_distributed做实验的时候，我发现当我把创建Session的代码改为：
`with tl.distributed.DistributedSession(task_spec=task_spec,checkpoint_dir="checkpoint",save_checkpoint_secs=1000,save_summaries_steps=100,save_summaries_secs=None) as sess:`
这时候会出现RuntimeError:"Global step should be created to use StepCounterHook."
另外单独指定task_spec和checkpoint_dir属性也会报错，
`tl.distributed.DistributedSession(task_spec=task_spec,checkpoint_dir="checkpoint") as sess:`
TypeError: unorderable types: object() > int()
这个错误可以通过指定save_summaries_steps和save_summaries_secs解决。
感觉tensorlayer对分布式的支持并不成熟，有很多问题。

**Comment by zsdonghao** [comment]
duplicate issue: https://github.com/tensorlayer/tensorlayer/issues/304
