### ISSUE TITLE
分布式在创建Session后导入模型npz文件出错

### ISSUE THREAD

**Issue by ning180** [tensorlayer/tensorlayer-chinese#33]
`with tl.distributed.DistributedSession(task_spec=task_spec) as sess:`
`    tl.files.load_and_assign_npz(sess=sess, name='n.npz', network=net)`
这样写会报错：
RuntimeError: Graph is finalized and cannot be modified.

**Comment by zsdonghao** [comment]
你好，我看到这个问题在英文github上已经在讨论了，这边先关闭了～
