### ISSUE TITLE
Translation in tutorial.rst

### ISSUE THREAD

**Issue by shorxp** [tensorlayer/tensorlayer-chinese#8]
- [x] Autoencoder is a unsupervised learning models which able to extract representative features, it has become more widely used for **learning generative models of data** and **Greedy layer-wise pre-train**. 
- 自编码器是一种能够提取具有代表性特征的无监督(Unsupervised)学习模型，
  它已经广泛使用于**数据生成模式的学习**与**逐层贪婪的预训练**(Greedy layer-wise pre-train)。
- [ ] Since every layer knows its immediate incoming layers, **the output layer (or output layers) of a network double as a handle to the network as a whole,** so usually this is the only thing we will pass on to the rest of the code.
- 由于每一层都知道它在一个网络中的直接输入层和（多个）输出接收层，**网络的输出层 double as a handle 对于网络作为一个整体，**所以通常这是我们唯一要传递给其他代码的内容。

重点在加粗的部分，有没有更加合适的翻译?

**Comment by zsdonghao** [comment]
自编码器是一种无监督学习（Unsupervisered Learning）模型，可从数据中学习出更好的表达，目前已经用于逐层贪婪的预训练（Greedy layer-wise pre-train）。
